post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      # Pods don't need code signing - prevents conflicts with manual signing of main target
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
      config.build_settings['CODE_SIGN_STYLE'] = 'Manual'
      config.build_settings.delete('PROVISIONING_PROFILE_SPECIFIER')
    end
  end
end
