# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

platform :ios do
  desc "Upload beta build to TestFlight (master branch)"
  lane :deploy_testflight do
    api_key = app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_KEY_CONTENT_BASE64'],
      is_key_content_base64: true,
    )

    changelog = changelog_from_git_commits(merge_commit_filtering: "exclude_merges")

    ipa_path = build_ios_ipa

    groups = ENV['TESTFLIGHT_GROUPS']&.split(',')&.map(&:strip)&.reject(&:empty?)
    has_groups = groups && !groups.empty?

    begin
      upload_to_testflight(
        api_key: api_key,
        ipa: ipa_path,
        changelog: changelog.to_s[0, 4000],
        distribute_external: has_groups,
        notify_external_testers: has_groups,
        groups: groups,
      )
    rescue => e
      raise e unless e.message.include?("Another build is in review")
      UI.important("Another build is in beta review - uploaded but skipped external distribution")
    end
  end

  desc "Upload release build to App Store (tags)"
  lane :deploy_appstore do
    api_key = app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_KEY_CONTENT_BASE64'],
      is_key_content_base64: true,
    )

    ipa_path = build_ios_ipa

    upload_to_app_store(
      api_key: api_key,
      ipa: ipa_path,
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: true,
      automatic_release: false,
      force: true,
    )
  end

  private_lane :build_ios_ipa do
    workspace = ENV['IOS_WORKSPACE']
    UI.user_error!("IOS_WORKSPACE env var not set - did the prepare step run?") unless workspace

    # Set provisioning profile only for the main app target (not Pods)
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "platforms/ios/IITCPrime.xcodeproj",
      team_id: ENV['APPLE_TEAM_ID'],
      code_sign_identity: "Apple Distribution",
      profile_uuid: ENV['PP_UUID'],
    )

    build_app(
      workspace: workspace,
      export_method: "app-store",
      xcargs: "DEVELOPMENT_TEAM=#{ENV['APPLE_TEAM_ID']} CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='Apple Distribution'",
      export_options: {
        signingStyle: "manual",
        teamID: ENV['APPLE_TEAM_ID'],
        provisioningProfiles: {
          "org.exarhteam.iitcprime" => ENV['PP_UUID'],
        },
      },
    )
  end
end

platform :android do
  desc "Deploy beta version to Google Play Store"
  lane :deploy_beta do
    changelog = changelog_from_git_commits(merge_commit_filtering: "exclude_merges")
    write_changelog(text: changelog)
    upload_to_play_store(
      track: "beta",
      package_name: "org.exarhteam.iitcprime",
      aab: "platforms/android/app/build/outputs/bundle/release/app-release.aab",
      json_key_data: ENV['GOOGLE_PLAY_ACCOUNT'],
      skip_upload_apk: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy production version to Google Play Store"
  lane :deploy_production do
    changelog = changelog_from_git_commits(merge_commit_filtering: "exclude_merges")
    write_changelog(text: changelog)
    upload_to_play_store(
      track: "production",
      package_name: "org.exarhteam.iitcprime",
      aab: "platforms/android/app/build/outputs/bundle/release/app-release.aab",
      json_key_data: ENV['GOOGLE_PLAY_ACCOUNT'],
      skip_upload_apk: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  private_lane :write_changelog do |options|
    changelogs_dir = File.join("fastlane", "metadata", "android", "en-US", "changelogs")
    FileUtils.mkdir_p(changelogs_dir)
    # Google Play limits changelog to 500 characters
    truncated = options[:text].to_s[0, 500]
    File.write(File.join(changelogs_dir, "default.txt"), truncated)
  end
end
