name: Make test build

on:
  pull_request:
  workflow_dispatch:

jobs:
  test_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Setup cache
        uses: ./.github/actions/setup-cache

      - name: Install dependencies
        run: npm install

      - name: Make test build
        run: npm run build:android:debug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-app-debug
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
